name: protdiff-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - torch==2.1.0
      - transformers==4.46.3
      - sentencepiece==0.2.0
      - scikit-learn==1.3.2
      - pandas==2.0.3
      - numpy==1.24.4
      - tqdm==4.67.1
      - biopython==1.83